### ISSUE TITLE
GeTor: Provide Tor Browser Bundle download file from Tor2web static URL

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/Tor2web#168]
This ticket is to provide Tor Browser Bundle download file from Tor2web static URL, such as /GetTor .

Nowdays downloading Tor is problematic, either in terms of usability, either in terms of accessibility of torproject.org from countries that apply censorship.

For that purpose we are going to implement the GetTor functionality on Tor2web, that will directly serve the latest stable TorBrowserBundle for the user language.

The TorBrowser will be served only for Windows and Mac OS X, where Desktop users are.

If the user language is not available from the ones supported by Tor, it shall default to English.

The /GetTor should detect if the user is already using Tor Browser Bundle and, in such care, redirect him to the TorProject download page.

The /GetTor should detect if the user is on iPhone and, in such case, redirect him to the OnionBrowser AppStore page.

The /GetTor should detect if the user is on Adroid and, in such case, redirect him to the OrBot Google Store page.

If the operating system is unknown, it shall provide an html or text file, saying that it cannot detect the user operating system, suggesting to manually access the torproject.org download web page (edge-case are not managed).

The latests version must be known/detected from https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions .

The file should be served to the end-user in a "streaming way", by avoiding buffering the download in Tor2web, as it would delay the Download window on the end-user side.

Whenever a specific version has been already downloaded, a cached copy must be kept on a Tor2web cache directory.

**Comment by ilv** [comment]
Great, thanks for the info. 

Regarding the code, I think it shouldn't be hard to accomplish. I understand what needs to be done, but as I'm not very familiar with tor2web yet, I'm still not sure if this should be added to an existing module or if I should create a separate script for it. Any guidance on what part of the code should I study or examples of other static URL handlers would be appreciated.

**Comment by fpietrosanti** [comment]
@ilv super! The code masters of Tor2web that can give you best insight to dig into the code are @evilaliv3 @virgil @hellais ! If you want to join irc channel we're at #tor2web on irc.oftc.net :)

**Comment by evilaliv3** [comment]
@ilv for what concern working on this ticket i think you have simply to concentrate on the feature and not in the t2w integration. that would be really easy.

if you want i think the best way to implement this feature is to proceed by writing a simple function that given some infos (the user User Agent is the only one meaningful i think) returns the official TBB download url to relocate the user on. to implement this probably you would require an automatically fetching of some urls from TBB; expect this data as static file on the filesystem and i will take care of fetch them for you.

what do you think?

**Comment by ilv** [comment]
Ok, thanks for the tip @evilaliv3. I think I found where the integration should be but I just haven't had the time to sit and do some code. In any case, I will concentrate on the feature for now, as you mention. About the fetching, if you have the time to do it, it would be great. Otherwise, I'm willing to do it (checking this the RecommendedTBBVersions url), as it would be of help for some stuff I'm doing at Tor.

**Comment by evilaliv3** [comment]
sure you have simply to tell me witch file do you want to be fetched
automatically and from where and i will manage to make it available to you
already parsed as a data structure that you can use to implement your
decision alghoritm.

let me know how to proceed!

**Comment by ilv** [comment]
Hi. Despite of what I thought, I actually had to run a tor2web node and modify t2w.py in order to see if what I was doing was correct. So, this is what I have so far (tried locally):

* Detect when user add /GeTor to an url and process it.
* Detect OS and language via User-Agent and Accept-Language.
* If user is using iPhone or Android, redirect her to the corresponding product stores.
* If user is using Tor Browser, redirect it to Tor Browser's downloads page.
* If user is using Linux, show her an error message.
* If user is using either Windows or Mac OS X, send her a ZIP file, depending on her OS and language. For now, I'm assuming that the Tor Browser files had already been downloaded and are available in a folder accessible by t2w. I'm not sure if this is the intended behaviour, though.

Is this near of what you had in mind?
You can check the modifications I've made here: https://github.com/ilv/Tor2web-3.0/tree/feature/gettor

Look forward to your feedback!

**Comment by virgil** [comment]
Just make GeTor a special subdomain.  So the link will be: GeTor.tor2web.org

-V

**Comment by fpietrosanti** [comment]
@virgil with a subdomain we would not have the "plausible deniability" feature (you may be visiting your favourite porn, instead of downloading TBB). I added #202 to track your feature idea

**Comment by fpietrosanti** [comment]
@ilv Sounds fine, perfect integration!

Regarding the language, also for OS X and Windows, we shall detect the user browser version/language and provide the TBB in the proper language.

Regarding the format, i see that the Windows Format is an executable while the Mac OS X format is a DMG file and not a ZIP file.

Then we shall integrate the automatic downloader component that keep in sync the downloaded TBB in that folder with the official TBB download page.
Those could run on startup or trough an automatic Twisted scheduler:
-  once every X in order to check if the local mirror of the latests version is complete.
- once every Y in order to check if there is a new TBB version, then make a new mirror, then replace the already downloaded one

We should be careful not to serve broken TBB package (ie: a user download from /GeTor when Tor2web is downloading a new package), so i suggest to first make a full-mirror of the latest-version, the made it available to the user.
Be carefu

**Comment by evilaliv3** [comment]
wait @fpietrosanti. imho all is good  apart the mirroring idea.

we can simply forward the user to the relevant page that depending on the
situation can be a direct downlooad (TBB), a fucking download page with
some logic (the apple store).

downloading directly and keeping in sync the mirror of all makes tor2web
became a monster and will make it lose a lot of bandwidth (i expect TBB
servers to have a better connection than the one of a volunteer).

what do you think?

**Comment by fpietrosanti** [comment]
@evilaliv3 I think that we can only manage this feature by providing *directly* to the end-user the relevant TBB installation file with no redirection what-so-ever (aside from Android/Apple things).

That's a requirement because this feature is designed to work in place where torproject.org domain is blocked.

So, the *latest* version of the TBB installation file must be served directly from Tor2web.

In order to serve the latest version of TBB installation file, the Tor2web software must have this file already stored on it's filesystem. 

In order to have it stored on the filesystem we must have it mirrored.

To have a full mirror of latest version of TBB on disk doesn't not require neither of a lot of data neither of a lot of bandwidth:

Considering the average size of TBB to be 25MB, the target platform to be Mac OS X (DMG) and Windows (EXE in 32bit and 64bit format), the amount of languages (15) we have 45 TBB installation file for about 1.1GB of disk space required/bandwidth. Considering the release of 1 new TBB per month, it's about 13.2GB of download bandwidth per year, that's nearly nothing.

**Comment by evilaliv3** [comment]
ok i see. i can manage to stream it from the upstream server (torproject.org, whatever) without problems so that we do not have to store it on the tor2web machine that can remain a lilliputian service.

**Comment by fpietrosanti** [comment]
@evilaliv3 We could serve a TBB file in streaming, but doing that way we would increase a lot the bandwidth required.

Not having a local mirror, to serve 10 times 1 TBB installation file in Arabic 32bit for Windows, it would require to download it 10 times from torproject.org. 

Instead, having a local mirror, would require it to download from torproject.org only 1 time. 

A possible solution "in the middle" is to serve the TBB installation file requested in streaming only the 1st time is requested, then keep a local cache only of that file. 

By the way, i think that's much easier/quicker to have always a stored local mirror of all TBB's latest versions, because it's a more deterministic process (ie: the GeTor always expect to have a local file of latests version available) and the code written to do it can be better re-used for other purposes.

**Comment by ilv** [comment]
@fpietrosanti great, thanks! The current code actually detects the language, so no problem there. I considered a zip file because I don't know how to send two files in a row with twisted. Of course, this is considering that we would send both files, the {.exe, .dmg} and the .asc signature file (right?). 

With respect to the mirroring, I also believe that the easier approach would be to have a local mirror of all Tor Browser's latest version (that's what the current code assumes). For this, a script in charge of detecting when a new version of Tor Browser is available (and download it) would be needed.

p.s. The sizes of Tor Browser for Windows and Mac OS X are about ~35Mb and ~42Mb.

**Comment by fpietrosanti** [comment]
@ilv Nice point on the .asc file! 
Thinking about it, i think that we should not send a zip bundle of the TBB file + the .asc, because the purpose of this functionality is to enable a third party to create an independent (private/uncensored) download website. So it's better to send directly to the end-user the .DMG and .EXE file.

With the regards to the .asc file, we think to have a simple parameters to be passed to the /GeTor in order to enable downloading the TBB file and the signature file separately. 

For example we may have URLs with parameters working as follow:
- /GetTor/file : gives you the latests TBB for your OS/Language
- /GetTor/signature : gives you the signature file for the latests TBB for your OS/Language

That way, the designer of the simplified download page, can setup a simplified download URL for both the TBB file and the signature file (in a similar way of https://www.torproject.org/projects/torbrowser.html.en).

But it's up to the user to download the signature file and verify it.

Regarding the size, assuming each TBB it's 38MB, currently the archive would require about 1.7GB of local disk storage, that's something available on a cheap $5/month VPS with 10GB of disk + 1TB/bandwidth. 

However, just as a consideration for the mirroring process, i think that we shall start delivering the new TBB version, only when the batch mirroring process of the new version has been completed. That's to be 100% sure to avoid sending back to the user broken-TBB-file (ie: A user X download from Tor2web TBB file, while this file is being downloaded by Tor2web from torproject.org, so the user X receive an incomplete/broken file).

**Comment by ilv** [comment]
@fpietrosanti Ok, I see. Having a separate URL for the signature sounds fine, there should always be the option to check the integrity of Tor Browser for those who want/know how to do it.

With respect to the mirroring process, I totally agree. The script designed to do the mirroring should safely replace the old bundles *after* the new ones have been downloaded.

**Comment by fpietrosanti** [comment]
@ilv good! After we'll have this /GeTor feature in place we could work on #220 following the idea of Virgil & the experience done with Amnesty, trying to make a super easy/hyper-cool-UX/internationalized Tor download page that use /GeTor, including instruction for verification!

**Comment by ilv** [comment]
Changes for supporting the request of Tor Browser (GetTor/file) and its signature (GetTor/signature) can be found on: https://github.com/ilv/Tor2web-3.0/tree/feature/gettor 

Since the code to process GetTor requests got larger, I took the liberty of creating a new module under utils/, minimizing the changes on t2w.py. Please note that this code considers that the files inside data/torbrowser do not have version numbers, instead they have the "latest" substring. This make things easier, but means that the script that automatically get the latest bundles should rename the files after moving the files into the download folder. What do you think of this?

**Comment by ilv** [comment]
Also, great! we should definitely work on #220 afterwards.

**Comment by fpietrosanti** [comment]
@ilv for the code review and integration @evilaliv3 is THE man! 

I agree about the the use of the "latest" approach, as we're going to serve always the latests version. We may also use the approach of symlinking "latests" to the "latests version number", for example if the latests if 4.0.5, there will be a directory called 4.0.5 and a symlink "latest -> 4.0.5" . 
That way when there is a new version (ie: 4.0.6), the mirroring process will start downloading TBB's in 4.0.6 and once finished, will change the "latest" symlink from 4.0.5 to 4.0.6, then delete 4.0.5 .

We could check for new version once per hour.

We shall probably do a "retry" for download of files during the mirroring before failing, in case of download error.

I think it's also useful to keep a detailed log of the mirroring and to trigger an email for un-recoverable error (ie: 3 times timeout or 3 times connection reset) ?

**Comment by ilv** [comment]
Ok @fpietrosanti, that sounds good!

@evilaliv3 I'm working on a script to fetch Tor Browser [here!](https://github.com/ilv/gettor/blob/develop/upload/fetch_latest_torbrowser.py), I think it would surely help for the mirroring.

**Comment by fpietrosanti** [comment]
@ilv super! I love you! Hugs! :* 
How to have the mirroring script to be scheduled (by Tor2web?) and to tell to Tor2web to start serving the new version?

**Comment by ilv** [comment]
@fpietrosanti :D 

Please note that the script still needs to be adapted for tor2web purposes. With respect to the scheduling, I was thinking on a cronjob that executes the script once a day maybe. Does that makes sense or you were thinking on something different? After downloading the new Tor Browser sucessfully, replacing the old files with the new ones should be enough to start serving the new version.

**Comment by ilv** [comment]
Script to fetch the latest Tor Browser (https://github.com/ilv/Tor2web-3.0/blob/feature/gettor/scripts/fetch_latest_torbrowser.py)[here]. There were some stuff that needed to be changed in utils/gettor.py and t2w.py in order to handle files by knowing the current version being served, so there is no need to rename the files after all. The script to fetch can filter by OS and LC. I didn't add ARCH (32/64-bit) as a paremeter because the only platform that have two separate files for this is Linux. The only thing left would be to find a way to schedule the fetching. 

@evilaliv3 what are your thoughts about the code?

**Comment by evilaliv3** [comment]
thanks @ilv 

i've still not found the time to work on this but i will surely do it at least on monday.

**Comment by ilv** [comment]
Ok, no problem! Look forward to your comments.

**Comment by evilaliv3** [comment]
hi ilv :)
the integration work you have done seems really good.

i left to you some comments https://github.com/ilv/Tor2web-3.0/commit/53b24be96785b27be4305245173fb5c99dec7282#diff-30a3b620fe85eee72563f0c3025c534fR87

@fpietrosanti / @hellais can you take a look also?

**Comment by fpietrosanti** [comment]
@evilaliv3 I would suggest to integrate everything (did you looked at https://github.com/ilv/Tor2web-3.0/tree/feature/gettor?) and then open-up bug fixes, otherwise we're blocked with amnesty delivery

**Comment by ilv** [comment]
Hi @evilaliv3 :-) 

Thanks for the feedback! All ok with the notes about the fetching script. However, I think you looked at an older version of t2w.py. Can you please take a look to the [most recent one](https://github.com/ilv/Tor2web-3.0/blob/feature/gettor/tor2web/t2w.py) and to the [gettor module](https://github.com/ilv/Tor2web-3.0/blob/feature/gettor/tor2web/utils/gettor.py) I added inside utils?

@fpietrosanti I'm ok with that option, in case @evilaliv3 agrees.

**Comment by evilaliv3** [comment]
i've commented commit by commit but i've also seen the latest one thanks.

i'm ok to start working on the integration on a branch and do not mind i will work readly on the fix related to:
1) https certificate validation
2) remove wget in place of a single Agent request

i'm confident to be able to do that in an hour or not more. i'm finishing to work on a deadline and i will start digging in it.

**Comment by evilaliv3** [comment]
thanks @ilv :)

**Comment by ilv** [comment]
Oh, my mistake then :P Thanks @evilaliv3 !

**Comment by evilaliv3** [comment]
okay @ilv i've opened this branch that already integrate all your work: https://github.com/globaleaks/Tor2web-3.0/tree/feature/gettor

i'm now going to apply the various changes i was suggesting and then i will write here about the possible missing things in order to finalize the feature.

**Comment by evilaliv3** [comment]
here we go @ilv: https://github.com/globaleaks/Tor2web-3.0/commit/f4bcd56397e9d5601e52443fba42204cbb071b24

With this commit the GetTor implementation is now based only on the Twisted library.

- TBB is now fetched by means of the LoopingCall mechanism
- Wget has been replaced by downloadPage
- HTTPS certificate validation has been enforced over all downloads
- Various paths have been sanitized from possible directory traversals

the only possible problems now are:
1) i don't think the Tor version detection will work as https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions is providing both a stable and an alpha and we are simply taking the last we get in our json parser but the order is not something we can trust; in the future it may change.
2)  for what concern locales i'm not perfectly sure that all browser will behave the same so probably we will need to correct the detection with some analisis of the user agents and capiTaL CASes and take care of locales differences like en-US / SR-rs etc. currrently in fact we are relying that all browsers use the exact locales that TBB uses that are now written here: https://github.com/globaleaks/Tor2web-3.0/blob/feature/gettor/data/lists/gettor_locales.txt

@hellais any suggestion for 1? @fpietrosanti for 1 & 2?

**Comment by evilaliv3** [comment]
here we go @ilv: https://github.com/globaleaks/Tor2web-3.0/commit/f4bcd56397e9d5601e52443fba42204cbb071b24

With this commit the GetTor implementation is now based only on the Twisted library.

- TBB is now fetched by means of the LoopingCall mechanism
- Wget has been replaced by downloadPage
- HTTPS certificate validation has been enforced over all downloads
- Various paths have been sanitized from possible directory traversals

the only possible problems now are:
1) i don't think the Tor version detection will work as https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions is providing both a stable and an alpha and we are simply taking the last we get in our json parser but the order is not something we can trust; in the future it may change.
2)  for what concern locales i'm not perfectly sure that all browser will behave the same so probably we will need to correct the detection with some analisis of the user agents and capiTaL CASes and take care of locales differences like en-US / SR-rs etc. currrently in fact we are relying that all browsers use the exact locales that TBB uses that are now written here: https://github.com/globaleaks/Tor2web-3.0/blob/feature/gettor/data/lists/gettor_locales.txt

@hellais any suggestion for 1? @fpietrosanti for 1 & 2?

**Comment by fpietrosanti** [comment]
@evilaliv3 for 1 i think that, because there will ever be 2 versions here (the latests stable and the latests experimental), we will need to pick-up the one with the "lower" version number

@evilaliv3 for 2 we can fix the problem my making a non-perfect match of the browser announced locale within the gettor locale. Es: If browser announce "whatever-CN" we will match "CN" within our gettor locale file to server the right TBB. 
Otherwise we shall look at what drupal does for browser_language_to_locale_mapping (see here https://www.drupal.org/node/365615), but given the relative low number of languages available in TBB i think we are fine.

@ilv it's probably useful to provide debugging and statistics:
                 a) logging of all requests with the browser user agent -> language detected -> served file (for debugging)
                 b) how many download has been served for each language over a period of time (for statistics)

**Comment by fpietrosanti** [comment]
From #tor-dev for 1:
mikeperry
9:16 naif: hrmm.. sorry, I was not happy about changing our version string format.. also, that file is becoming less important with our firefox-based updater, but you probably don't want to speak it's crazy XML dialect..
9:16
mikeperry
9:16 naif: from now on, I think "anything that doesn't have a letter before the first dash" will do for that file
mikeperry
9:17 first dash, or end of string

**Comment by evilaliv3** [comment]
@fpietrosanti regarding the version its not real that they will always have 2 versions, one alpha and a stable.
they still have no idea of how to standardize it (https://trac.torproject.org/projects/tor/ticket/14383) and during time they had the following conditions(https://github.com/globaleaks/Tor2web-3.0/commit/f4bcd56397e9d5601e52443fba42204cbb071b24#commitcomment-9815896): 
- sometimes they had only a stable version
- sometimes they had one stable and one alpha
- sometimes they has one stable and multiple alpha

in addition the version format is not a standard one so that it's tricky to find an algorithm that permit to make comparison.

to answer mike for sure suggestion to host both have you already clarified that our intent is to chose the version/language on behalf of the user so to simplify TBB adoption?

based on mikeperry clarification the alghoritm i'm thinking by the way should be:
1) first remove the version that containt a dash
2) second compare the remaining ones by using from distutils.version.LooseVersion (that is deprecated and in the future will be probably replaced by Normalized Version)

@mmaker do you have any suggestion?

**Comment by evilaliv3** [comment]
@adrelanos / @micahflee: what is your suggestion given the experience with tb-updater and torbrowser-launcher?

**Comment by adrelanos** [comment]
It's a mess. It really is.

We plan on recommending the lowest version number that RecommendedTBBVersions suggests to make sure we got a stable version. (It will still be considered secure, otherwise it would not be inside RecommendedTBBVersions.) Additionally, for those unhappy with the default suggestion, we plan on providing a selection menu, where users can choose higher version numbers advertised by RecommendedTBBVersions.

In future, perhaps `getinfo consensus/packages`, that was introduced in `tor` `0.2.6.3-alpha` might provide a reliable way to detect the latest stable version in a secure way. (Reference: https://trac.torproject.org/projects/tor/ticket/10395)

**Comment by adrelanos** [comment]
> The TorBrowser will be served only for Windows and Mac OS X, where Desktop users are.

No Linux support? That's a pity. Would Linux support really be considerable more effort since you plan on supporting iphone and android as well?

**Comment by evilaliv3** [comment]
@adrelanos:
1) what kind of macical code have you found working in comparing version written that way? do you think this alghorithm may work in general give your experience in past version names?:

    first: remove the version that containt a dash
    second: compare the remaining ones by using from distutils.version.LooseVersion (that is deprecated and in the future will be probably replaced by Normalized Version)

2) In this first implementation we do not need to support Linux as the idea of this gettor implementation is to simplify the adoption of TBB for not skilled users while for a matter of generalization a linux user already know somehow how to install a software and also found tor in his distro; anyway this topic is under discussion.

**Comment by fpietrosanti** [comment]
@adrelanos are you coming to Valencia for the Tor Dev Meeting early next month? With you, us and some other it would be very nice to make a sort of "Tor Third Party Software Integration Session" to discuss what do we need/feel as third party software developer that integrate and use Tor in other projects!

**Comment by adrelanos** [comment]
> With you, us and some other it would be very nice to make a sort of "Tor Third Party Software Integration Session" to discuss what do we need/feel as third party software developer that integrate and use Tor in other projects!

That would be cool, but...

> @adrelanos are you coming to Valencia for the Tor Dev Meeting early next month?

Low, non-zero probability. (I mailed my funding request at travel [at] torproject.org a bit late at 02/12/2015 because I didn't know that kind of sponsorship exists. Haven't got a reply yet, perhaps because it was too late.)

**Comment by adrelanos** [comment]
> 1) what kind of macical code have you found working in comparing version written that way?

https://github.com/Whonix/tb-updater/blob/master/usr/lib/tbbversion_parser

```
sort --unique --version-sort --reverse
```

> do you think this alghorithm may work in general give your experience in past version names?:

Probably not forever.

> first: remove the version that containt a dash

It's not guaranteed, that there will always be dashes. I should have kept a history of existing tbb version files.

> second: compare the remaining ones by using from distutils.version.LooseVersion (that is deprecated and in the future will be probably replaced by Normalized Version)

Make sure it won't break if it's invalid json, any quotes or braces forgotten.

`getinfo consensus/packages` is my new hope to settle this once and forever. Otherwise I was considering to notify admins when RecommendedTBBVersions changed and to parse it using my brain, then manually updating a self-hosted version file. One could argue, that it would be less trustworthy. On the other hand, see also: https://trac.torproject.org/projects/tor/ticket/13065

**Comment by evilaliv3** [comment]
thank you @adrelanos: @fpietrosanti you see, it seem that the format used is not so standard :)

by the way let see what will happen with the code i've currently implemented.

**Comment by ilv** [comment]
Awesome @evilaliv3! the changes look really great, thanks :)

For 1) what about having an own tor2web.org/LatestTB url, specifying a "more standard" format, and if something happens in RecommendedTBBVersions, you make the necessary changes on tor2web.org/LatestTB to keep providing the format you specified (and thus the other nodes won't have to worry about it)?

**Comment by evilaliv3** [comment]
@ilv we won't have central nodes in the tor2web architecture; in our mind all nodes should be independent.
by the way le'ts discuss of the benefits of such a solution if you see some.

**Comment by evilaliv3** [comment]
i've resumed my experience and suggestions in implementing the gettor functionality on https://trac.torproject.org/projects/tor/ticket/14383#comment:5. this way we can try together try to help TBB specifying a usable API for RecommendedTBBVersions.

if you have any additional comments fill them on https://trac.torproject.org/projects/tor/ticket/14383

**Comment by ilv** [comment]
Well, the main benefit I see is that if/when the format of RecommendedTBBVersions change, nodes with gettor will not be affected as long as the /LatestTB adapts its result. 

Of course, other option is to provide feedback and help on the ticket you mentioned. I'll see if I can add some more feedback, thanks for the link.

**Comment by fpietrosanti** [comment]
To be done the documentation at https://github.com/globaleaks/Tor2web-3.0/wiki/GetTor /cc @ilv @evilaliv3

**Comment by evilaliv3** [comment]
we should start a single unified name beteen GetTor and GeTor, i prefer the fist and all the code/wiki pages of Tor2web use currently GetTor.

@ilv take your choice ;)

**Comment by evilaliv3** [comment]
current work has been integrated by me in master and released in 3.1.39!

let's way for the bugs that will raise and then we can push out a public announcement!

**Comment by ilv** [comment]
Alright @fpietrosanti, I'll try to add my two cents in the documentation.

@evilaliv3 Yes, I noticed about the integration of GetTor in 3.1.39, great!
And I definitely prefer **GetTor** :)

**Comment by fpietrosanti** [comment]
This has been implemented and documented

**Comment by evilaliv3** [comment]
@fpietrosanti i've found that the API is now serving two stample release version and we are serving the oldest one; the fact that the tor recomended versions API is not well defined is a problem:

https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions

    [
    "4.5.2",
    "4.5.2-Linux",
    "4.5.2-MacOS",
    "4.5.2-Windows",
    "4.5.3",
    "4.5.3-Linux",
    "4.5.3-MacOS",
    "4.5.3-Windows",
    "5.0a2",
    "5.0a2-Linux",
    "5.0a2-MacOS",
    "5.0a2-Windows"
]

here currently our getttor implementation is going to use 4.5.2.

in fact we written the algorithm in order to select the oldest version expecting to have a stable and an alpha and due to the fact that we it's not easy to idcerna sable version from alpha versions.

@ilv do you have any suggestion?

**Comment by fpietrosanti** [comment]
Added ticket at Tor Project https://trac.torproject.org/projects/tor/ticket/16551

**Comment by ilv** [comment]
@fpietrosanti @evilaliv3 I totally forgot abut this, sorry. Let's keep the discussion on trac.
