### ISSUE TITLE
tor2web won't start for me

### ISSUE THREAD

**Issue by Talicada** [globaleaks/Tor2web#241]
Every time I try to start it, it fails. I've tried to find where any logs are located but can't find anything. I have turned debugging on and no logs are to be seen. Any ideas? and yes I followed the install and config guides.

**Comment by evilaliv3** [comment]
hi @Talicada,
can you please clarify what is the distribution you are running on?
Tor2web need a bit of configuration right now in order to start and the main possibilities for a failure are:
1) you are running on a system that do not support apparmor (if this is such a condition disable it from /etc/defaults/tor2web
2) you have not configured all the needed variables in /etc/tor2web.conf

if you could provide more details i would try to help you.
you find us all on irc on OFTC on the #tor2web channel

**Comment by Talicada** [comment]
Ubuntu 14.04, I believe that I have configured it well enough.

 

I get this error when starting it:

 

# /etc/init.d/tor2web start

   ...fail!

 

And this is my current config, with important information changed:

http://pastebin.com/raw.php?i=Vv9d9ta1

Thanks,

Ashley Jackson

**Comment by evilaliv3** [comment]
closing this as outdated.

let me know @Talicada if you still have issues on this.
