### ISSUE TITLE
Bad URL Fix

### ISSUE THREAD

**Issue by ungenannter** [globaleaks/Tor2web#287]
Some links are incorrectly rewritten on onion.to:

UPDATE: sorry, i posted the wrong url
OLD: example: https://dirnxxdraygbifgc.onion.to -> https:http://dirnxxdraygbifgc.onion.to.to
NEW: example: https://dirnxxdraygbifgc.onion.to -> https://dirnxxdraygbifgc.onion.to.to

Example site: https://edaethwo3476axnq.onion.to/

also check #112

**Comment by evilaliv3** [comment]
@ungenannter is this happening on the latest version or what?

have you already diagnosed the issue?

does this happen also on the current  https:http://dirnxxdraygbifgc.tor2web.org on tor2web.org domain?

**Comment by virgil** [comment]
This happens when the url-rewriting script is run twice on the same content.  Usually due to some sort of funny buffering.  It also goes away if you set avoid_overwriting_visible_content = True .

**Comment by ungenannter** [comment]
Here is a example: https://edaethwo3476axnq.onion.to/

**Comment by evilaliv3** [comment]
ok thanks, i will experiment in localhost using "onion.to" to fix it if the bug exist in the latest tor2web version.

is onion.to running the latest one?

**Comment by virgil** [comment]
It's a bug in the latest version.  But don't know what version onion.to is
running.

It comes from running the regex twice on the same content.

**Comment by ungenannter** [comment]
onion.to is running: 3.1.48. I guess this is the latest version.

**Comment by evilaliv3** [comment]
Okay i got an idea on the possible issue.

In tor2web we have a replacement windo f 1000characters that slides and push out 500 characters at a time so that obviously can pass on the same url 2 times, but is the reasonable size to keep the internal buffering low
.
Generally passing on the same url multiple times does not cause any issue; but this failing on all tor2web domains like onion.something (e.g. onion.city, onion.to, onion.cab).

the issue exists since the time we added replacements for onion hidden services using HTTPS like https://antani.onion; passing two times over this link does:
-> https://antani.onion -> https://antani.onion.to -> https://antani.onion.to.to

i think we should simply work on the regexp https://github.com/globaleaks/Tor2web/blob/master/tor2web/t2w.py#L1509 in order to simply assuring to to replacement when the ".onion" is not followed by a "." character. like in "antani.onion.city".

@virgil @obtuse could some of you try this change on onion.city/onion.link and provide a patch? take care that this fix should be aplplied also to other regexps like the one for set-cookie.

**Comment by evilaliv3** [comment]
fixed! i will take of releasing it later today in 3.1.50

**Comment by evilaliv3** [comment]
ok out there is a 3.1.51 that include the fix.

@ungenannter would you please try it and confirm that the issue is fixed?

**Comment by ungenannter** [comment]
Look good. Thank you!
