### ISSUE TITLE
/antanistaticmap/stats/yesterday works for each subdomain but it's cached separately

### ISSUE THREAD

**Issue by turboMaCk** [globaleaks/Tor2web#289]
Hello!

I think I find some issue that allow attacker to force tor2web perform computation heavy stuff easily.

You can use {whatever}.tor2web.org/antanistaticmap/stats/yesterday to get stats. Doing so enforce service to create new cache if it does not exist. 

I also found that response for all valid proxies is the same but cache for result is not shared:
https://eqt5g4fuenphqinx.tor2web.org/antanistaticmap/stats/yesterday
https://duskgytldkxiuqc6.tor2web.org/antanistaticmap/stats/yesterday

Even on invalid subdomains computation happens:
https://imnothere.tor2web.org/antanistaticmap/stats/yesterday

**Comment by evilaliv3** [comment]
@turboMaCk i do not think i get the point. coculd you please clarify around my points

1. yes it's possible to get the stats on every whatever domain, but the cache returned is always the same with no allocation; the entry is cached only when a new exsisting hidden service is found so that an other time 'whatever' does not cause any allocation.

2. yep by design the nodes are not interconnected so they share only their point of view

3. yep also ringobongo.tor2web.orrg works!

if i've missed something please reopen the ticket :)
