### ISSUE TITLE
Tor2web AppArmor profile not found

### ISSUE THREAD

**Issue by fiyona** [globaleaks/Tor2web#323]
aa-exec: ERROR: profile 'usr.bin.tor2web' does not exist

 * Tor2web is not running
 how do i go about this

**Comment by fiyona** [comment]
service tor2web status
Letsencrypt detected, fixing permission for /etc/letsencrypt/{live,archive} for tor2web user
 * Enabling Tor2web Apparmor Sandboxing...                                                                                             aa-exec: ERROR: profile 'usr.bin.tor2web' does not exist

 * Tor2web is not running

**Comment by fiyona** [comment]
Help om fixing this errer

**Comment by NSkelsey** [comment]
Hi @fiyona,

It looks like you need to disable Apparmor Sandboxing. You can do this by changing the configuration `APPARMOR_SANDBOXING=1` to `APPARMOR_SANDBOXING=0` in the file `/etc/default/tor2web`.

Once you do that restart the service.

If that does not work, it may be because you have customized the installation and if that is the case it may just be easier and faster to start with a fresh machine and perform the full re-installation.

Hope this helps.

**Comment by fiyona** [comment]
hello,

i have done as guided here but now no error has come up but when i check
the status of Tor2web,

its still not running

**Comment by evilaliv3** [comment]
Closing as outdated.
