### ISSUE TITLE
Add support for Debian Buster (10)

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/Tor2web#362]
This ticket is to keep track of the activities necessary for adding and bugfixing the support for the latest Debian stable: Buster (10).

**Comment by evilaliv3** [comment]
We could probably keep as reference the packaging of GlobaLeaks: https://github.com/globaleaks/GlobaLeaks/issues/2676

**Comment by fpietrosanti** [comment]
As always, integrating the tor2web code in globaleaks package, would make
much simpler/secure and diffused the tor2web sw:-)

Sent from mobile

On 29 Sep 2019, at 20:32, Giovanni Pellerano <notifications@github.com>
wrote:

We could probably keep as reference the packaging of GlobaLeaks:
globaleaks/GlobaLeaks#2676
<https://github.com/globaleaks/GlobaLeaks/issues/2676>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/globaleaks/Tor2web/issues/362?email_source=notifications&email_token=AAF4CO7HG7AOR7HOCUVXU4DQMDYCNA5CNFSM4I3TQEHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD733SXI#issuecomment-536328541>,
or mute the thread

**Comment by evilaliv3** [comment]
KISS!

**Comment by evilaliv3** [comment]
Done! Actually i consider that as for [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks), Debian Buster is now the best and up to date system  for which we have a package. Let's start recommending it!
